### PR TITLE
Readme: initialize and repo repo sync :p

### PR DESCRIPTION
**Pull request by vibhu0009**
Am sure everyone needs it :p

### CODE REVIEW

**Comment by smartAgent47** [comment]
Hello brother,

Nice to see you for having interest in Raxfian OS. Brother after you sync
if you are, there are latest r26 M releases which are not merged in raxfian
repos .. So if you want to build, you need to merge latest changes from
android.googlesource.com and then build. And if you merged and it got
built, please make a pull request so that i can merge the pull request .

Anyways i am syncing my project again because i messed it up in merging d
latest changes..

Thanks Again

**Comment by vibhu0009** [comment]
Sure I will try it n let u know.. :) :) 

Sent from YU

On Nov 3, 2015 10:18 PM, Idrees Dargahwala <notifications@github.com> wrote:

Hello brother,

Nice to see you for having interest in Raxfian OS. Brother after you sync
if you are, there are latest r26 M releases which are not merged in raxfian
repos .. So if you want to build, you need to merge latest changes from
android.googlesource.com and then build. And if you merged and it got
built, please make a pull request so that i can merge the pull request .

Anyways i am syncing my project again because i messed it up in merging d
latest changes..

Thanks Again

**Comment by vibhu0009** [comment]
I will try with r26 n see how it goes... :) 

Sent from YU

On Nov 3, 2015 10:23 PM, Vibhor <cvibhu0009@gmail.com> wrote:

Sure I will try it n let u know.. :) :) 

Sent from YU

On Nov 3, 2015 10:18 PM, Idrees Dargahwala <notifications@github.com> wrote:

Hello brother,

Nice to see you for having interest in Raxfian OS. Brother after you sync
if you are, there are latest r26 M releases which are not merged in raxfian
repos .. So if you want to build, you need to merge latest changes from
android.googlesource.com and then build. And if you merged and it got
built, please make a pull request so that i can merge the pull request .

Anyways i am syncing my project again because i messed it up in merging d
latest changes..

Thanks Again

**Comment by smartAgent47** [comment]
I guess it will not work bcoz i already tried it nd ended up in a build
error .. So changes are needed i guess ..

Anyways try !

Thanks

**Pull request merged**
